server:
  port: 8700
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8600/eureka/
zuul:
  routes:
    ms-archives-api:
      path: /api/archives/**
      serviceId: ms-plugin-archives
      stripPrefix: false
    ms-pages:
      path: /pages/**
      serviceId: ms-plugin-pages
      stripPrefix: false

#    ms-users:
#      path: /users/**
#      serviceId: ms-plugin-users
#    ms-login:
#      path: /login
#      serviceId: ms-plugin-users
#      stripPrefix: false
#    ms-users-api:
#      path: /api/users/**
#      serviceId: ms-plugin-users
#      stripPrefix: false
logging:
  level: debug
spring:
  thymeleaf:
    cache: false
  mvc:
    static-path-pattern: /static/**
#  resources:
#    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/