server:
  port: 8700
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8600/eureka/
zuul:
  routes:
    ms-archives:
      path: /archives/**
      serviceId: ms-plugin-archives
    ms-pages:
      path: /pages/**
      serviceId: ms-plugin-pages
    ms-users:
      path: /users/**
      serviceId: ms-plugin-users
    ms-login:
      path: /login
      serviceId: ms-plugin-users
      stripPrefix: false
    ms-users-api:
      path: /api/users/**
      serviceId: ms-plugin-users
      stripPrefix: false
security:
  basic:
    enabled: true
logging:
  level: debug