spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/minesitex?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8&serverTimezone=GMT%2b8
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
