server:
  port: 8700

zuul:
  routes:
    msx-articles-api:
      path: /api/user/**
      serviceId: msx-plugin-user
      stripPrefix: false
    msx-pages:
      path: /movie/**
      serviceId: msx-plugin-movie
      stripPrefix: false

#    msx-users:
#      path: /users/**
#      serviceId: msx-plugin-users
#    msx-login:
#      path: /login
#      serviceId: msx-plugin-users
#      stripPrefix: false
#    msx-users-api:
#      path: /api/users/**
#      serviceId: msx-plugin-users
#      stripPrefix: false
spring:
  thymeleaf:
    cache: false
  mvc:
    static-path-pattern: /static/**
#  resources:
#    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/


jwt:
  header: Authorization
  secret: MinesiteX
  expiration: 604800
  tokenHead: "MinesiteX "
