eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8600/eureka/
feign:
  compression:
    request:
      mime-types: application/json,text/xml,application/xml
      min-request-size: 2048
server:
  compression:
    enabled: true
    mime-types: application/json,text/xml,application/xml
    min-response-size: 2048

msx:
  jwt:
    header: Authorization
    secret: msx-jwt
    expiration: 604800000
    tokenHead: "Bearer "

  wx:
    appId: wx01
    appSecret: wx01
    token: wx01
    key: wx01
    openId: wx01

  wxexp:
    appId: wx02
    appSecret: wx02
    token: wx02
    key: wx02
    openId: wx02
    tpl: wx02

  secret:
    key: msx-key
