server:
  port: 8700

zuul:
  routes:
    msx-wx:
      path: /wx/**
      serviceId: msx-service-wx
      stripPrefix: false
    msx-user:
      path: /user/**
      serviceId: msx-service-user
      stripPrefix: false
    msx-movie:
      path: /movie/**
      serviceId: msx-service-movie
      stripPrefix: false
    msx-movie:
      path: /assignment/**
      serviceId: msx-service-assignment
      stripPrefix: false
    msx-movie:
      path: /admin/**
      serviceId: msx-service-admin
      stripPrefix: false

#    msx-users:
#      path: /users/**
#      serviceId: msx-plugin-users
#    msx-login:
#      path: /login
#      serviceId: msx-plugin-users
#      stripPrefix: false
#    msx-users-api:
#      path: /api/users/**
#      serviceId: msx-plugin-users
#      stripPrefix: false
spring:
  thymeleaf:
    cache: false
  mvc:
    static-path-pattern: /static/**
#  resources:
#    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/
