server:
  port: 8800
  compression:
    enabled: true
    mime-types: application/json,text/xml,application/xml
    min-response-size: 2048

spring:
  application:
    name: msx-web-aio
  profiles:
    active: msx-web-aio

  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    content-type: text/html
    mode: HTML5

  mvc:
    static-path-pattern: /static/**
#  resources:
#    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/

  # spring data redis 配置
  redis:
    # Redis数据库索引（默认为0）
    database: 0
    # Redis服务器地址
    host: 127.0.0.1
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    password:
    # 连接池最大连接数（使用负值表示没有限制）
    pool.max-active: 8
    # 连接池最大阻塞等待时间（使用负值表示没有限制）
    pool.max-wait: -1
    # 连接池中的最大空闲连接
    pool.max-idle: 8
    # 连接池中的最小空闲连接
    pool.min-idle: 0
    # 连接超时时间（毫秒）
    timeout: 0

  # spring data jpa + mysql 配置
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/minesitex?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8&useSSL=false&serverTimezone=GMT%2b8
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  # spring data mongodb 配置
  data:
    mongodb:
      uri: mongodb://localhost:27017/minesitex

logging:
  level: debug

msx:
  jwt:
    header: Authorization
    secret: msx-jwt
    expiration: 604800000
    tokenHead: "Bearer "

  wx:
    appId: wx01
    appSecret: wx01
    token: wx01
    key: wx01
    openId: wx01

  wxexp:
    appId: wx02
    appSecret: wx02
    token: wx02
    key: wx02
    openId: wx02
    tpl: wx02

  secret:
    key: msx-key
