server:
  port: 8700
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8600/eureka/
zuul:
  routes:
    mt-archives:
      path: /archives/**
      serviceId: mt-plugin-archives
    mt-pages:
      path: /pages/**
      serviceId: mt-plugin-pages
    mt-users:
      path: /users/**
      serviceId: mt-plugin-users
    mt-login:
      path: /signin
      serviceId: mt-plugin-users
      stripPrefix: false
    mt-users-api:
      path: /api/users/**
      serviceId: mt-plugin-users
      stripPrefix: false
security:
  basic:
    enabled: true
logging:
  level: debug